# Generated by Django 4.2.23 on 2025-06-14 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.CharField(help_text='ID of the user who submitted the report', max_length=255)),
                ('image_url', models.URLField(help_text='URL of the image associated with the report', max_length=500)),
                ('report_data', models.JSONField(help_text='JSON data containing details of the report')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', help_text='Status of the report (e.g., pending, resolved)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
