# Generated by Django 4.2.23 on 2025-08-04 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injuryreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reportstatushistory',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='injuryreport',
            name='ngo',
        ),
        migrations.RemoveField(
            model_name='injuryreport',
            name='report_data',
        ),
        migrations.AddField(
            model_name='expopushtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expopushtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='age',
            field=models.CharField(blank=True, help_text='Age estimate with reasoning', max_length=100),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='ai_analysis',
            field=models.JSONField(default=dict, help_text='Complete AI analysis results'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='behavior',
            field=models.CharField(blank=True, help_text='Observed behavior', max_length=200),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='breed',
            field=models.CharField(blank=True, help_text='Breed or breed mix', max_length=100),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='care_tips',
            field=models.JSONField(default=list, help_text='AI-generated care recommendations'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='confidence_score',
            field=models.IntegerField(blank=True, help_text='Overall analysis confidence 1-10', null=True),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='context',
            field=models.CharField(blank=True, help_text='Situation assessment', max_length=100),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='description',
            field=models.TextField(blank=True, help_text="Detailed description of the animal's condition"),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='environment_factors',
            field=models.TextField(blank=True, help_text='Environmental conditions affecting the animal'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='gender',
            field=models.CharField(blank=True, help_text='Male/Female/Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='immediate_actions',
            field=models.JSONField(default=list, help_text='Immediate action steps'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='injury_summary',
            field=models.TextField(blank=True, help_text='Detailed injury description'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='severity',
            field=models.CharField(blank=True, help_text='Critical/High/Moderate/Low', max_length=50),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='species',
            field=models.CharField(blank=True, help_text='Animal species (e.g., Canine, Feline)', max_length=100),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='symptoms',
            field=models.JSONField(default=list, help_text='List of visible symptoms'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='title',
            field=models.CharField(blank=True, help_text='AI-generated descriptive title', max_length=500),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='urgency',
            field=models.CharField(blank=True, help_text='Medical priority level', max_length=50),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='weight',
            field=models.CharField(blank=True, help_text='Weight estimate', max_length=100),
        ),
        migrations.AddField(
            model_name='reportstatushistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the status change'),
        ),
        migrations.AddField(
            model_name='reportstatushistory',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who updated the status', max_length=255),
        ),
        migrations.AddIndex(
            model_name='injuryreport',
            index=models.Index(fields=['status'], name='reports_inj_status_4f5267_idx'),
        ),
        migrations.AddIndex(
            model_name='injuryreport',
            index=models.Index(fields=['severity'], name='reports_inj_severit_58b8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='injuryreport',
            index=models.Index(fields=['urgency'], name='reports_inj_urgency_5b4f49_idx'),
        ),
        migrations.AddIndex(
            model_name='injuryreport',
            index=models.Index(fields=['created_at'], name='reports_inj_created_8bacba_idx'),
        ),
        migrations.AddIndex(
            model_name='injuryreport',
            index=models.Index(fields=['latitude', 'longitude'], name='reports_inj_latitud_f8f819_idx'),
        ),
    ]
