# Generated by Django 4.2.23 on 2025-08-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_injuryreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuryreport',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='ai_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='behavior',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='care_tips',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='confidence_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='context',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='environment_factors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='immediate_actions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='injury_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='severity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='species',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='symptoms',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='urgency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
