# Generated by Django 4.2.23 on 2025-06-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
        ('reports', '0002_injuryreport_ngo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='ngo_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_taken_by', to='ngo.ngo'),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='ngo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created_by', to='ngo.ngo'),
        ),
    ]
