# Generated by Django 4.2.23 on 2025-08-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_injuryreport_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpoPushToken',
        ),
    ]
