# Generated by Django 4.2.23 on 2025-06-24 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstatushistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportstatushistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reports.injuryreport'),
        ),
    ]
