# Generated by Django 4.2.23 on 2025-06-29 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '__first__'),
        ('reports', '0005_alter_reportstatushistory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryreport',
            name='volunteer_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_taken_by_volunteer', to='user.userprofile'),
        ),
    ]
