# Generated by Django 4.2.23 on 2025-06-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('animal', 'Animal Welfare'), ('environment', 'Environment'), ('medical', 'Medical Aid'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
            ],
        ),
    ]
