# Generated by Django 4.2.23 on 2025-06-23 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='ngo_id',
            new_name='appwrite_user_id',
        ),
        migrations.AddField(
            model_name='ngo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ngo',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
    ]
