# Generated by Django 4.2.23 on 2025-06-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_rename_ngo_id_ngo_appwrite_user_id_ngo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
