# Generated by Django 4.2.23 on 2025-08-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appwrite_user_id', models.CharField(db_index=True, max_length=255)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to='users.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['appwrite_user_id'], name='users_userp_appwrit_d4d91d_idx'), models.Index(fields=['is_active'], name='users_userp_is_acti_ca9ccb_idx')],
                'unique_together': {('user', 'token')},
            },
        ),
    ]
