# Generated by Django 4.2.23 on 2025-08-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpushtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appwrite_user_id', models.CharField(db_index=True, max_length=255)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('user_type', models.CharField(choices=[('user', 'User'), ('ngo', 'NGO')], default='user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['appwrite_user_id'], name='users_pusht_appwrit_fb707a_idx'), models.Index(fields=['is_active'], name='users_pusht_is_acti_de984b_idx'), models.Index(fields=['user_type'], name='users_pusht_user_ty_d42f76_idx')],
                'unique_together': {('appwrite_user_id', 'token')},
            },
        ),
    ]
