# Generated by Django 4.2.23 on 2025-06-24 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0005_alter_reportstatushistory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.CharField(max_length=255)),
                ('recipient_type', models.CharField(choices=[('ngo', 'NGO'), ('user', 'User')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.injuryreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
