# Generated by Django 4.2.23 on 2025-08-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # Drop the new tables we just created since they conflict
        migrations.RunSQL(
            "DROP TABLE IF EXISTS notifications_notification CASCADE;",
            reverse_sql="-- Cannot reverse drop table"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS notifications_notificationpreferences CASCADE;",
            reverse_sql="-- Cannot reverse drop table"
        ),
        
        # Rename the existing table to match our model
        migrations.RunSQL(
            "ALTER TABLE notifications_notificationhistory RENAME TO notifications_notification;",
            reverse_sql="ALTER TABLE notifications_notification RENAME TO notifications_notificationhistory;"
        ),
        
        # Rename columns to match our model
        migrations.RunSQL(
            "ALTER TABLE notifications_notification RENAME COLUMN notification_id TO id;",
            reverse_sql="ALTER TABLE notifications_notification RENAME COLUMN id TO notification_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE notifications_notification RENAME COLUMN recipient_id TO recipient_user_id;",
            reverse_sql="ALTER TABLE notifications_notification RENAME COLUMN recipient_user_id TO recipient_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE notifications_notification RENAME COLUMN notification_type TO type;",
            reverse_sql="ALTER TABLE notifications_notification RENAME COLUMN type TO notification_type;"
        ),
        
        # Drop columns we don't need
        migrations.RunSQL(
            "ALTER TABLE notifications_notification DROP COLUMN IF EXISTS recipient_type;",
            reverse_sql="-- Cannot reverse drop column"
        ),
        migrations.RunSQL(
            "ALTER TABLE notifications_notification DROP COLUMN IF EXISTS status;",
            reverse_sql="-- Cannot reverse drop column"
        ),
        migrations.RunSQL(
            "ALTER TABLE notifications_notification DROP COLUMN IF EXISTS report_id;",
            reverse_sql="-- Cannot reverse drop column"
        ),
        migrations.RunSQL(
            "ALTER TABLE notifications_notification DROP COLUMN IF EXISTS delivered_at;",
            reverse_sql="-- Cannot reverse drop column"
        ),
        
        # Create NotificationPreferences table manually
        migrations.RunSQL(
            """
            CREATE TABLE notifications_notificationpreferences (
                id BIGSERIAL PRIMARY KEY,
                user_id VARCHAR(255) UNIQUE NOT NULL,
                emergency_alerts BOOLEAN DEFAULT TRUE,
                status_updates BOOLEAN DEFAULT TRUE,
                general_announcements BOOLEAN DEFAULT TRUE,
                injury_reports BOOLEAN DEFAULT TRUE,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            );
            """,
            reverse_sql="DROP TABLE notifications_notificationpreferences;"
        ),
    ]
