# Generated by Django 4.2.23 on 2025-08-15 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_injuryreport_age_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='notification_type',
            field=models.CharField(choices=[('emergency', 'Emergency Alert'), ('status_update', 'Status Update'), ('injury_report', 'Injury Report'), ('general', 'General Announcement'), ('volunteer', 'Volunteer Notification')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='recipient_type',
            field=models.CharField(choices=[('user', 'User'), ('ngo', 'NGO'), ('volunteer', 'Volunteer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.injuryreport'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['recipient_id', 'is_read'], name='notificatio_recipie_f753ca_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_8bb07f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['is_urgent'], name='notificatio_is_urge_8036b7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['created_at'], name='notificatio_created_ba4873_idx'),
        ),
    ]
