# Generated by Django 4.2.23 on 2025-08-15 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationhistory_delivered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='notification_type',
            field=models.CharField(choices=[('emergency', 'Emergency Alert'), ('status_update', 'Status Update'), ('injury_report', 'Injury Report'), ('general', 'General Announcement'), ('volunteer', 'Volunteer Notification')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
