# Generated by Django 4.2.23 on 2025-08-15 19:35

from django.db import migrations


def fix_notification_table(apps, schema_editor):
    """Drop the old notificationhistory table and let Django create the correct one"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Drop the old table if it exists
        cursor.execute("DROP TABLE IF EXISTS notifications_notificationhistory CASCADE;")


def reverse_fix_notification_table(apps, schema_editor):
    """This is irreversible - we can't recreate the old table structure"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20250815_1935'),
    ]

    operations = [
        migrations.RunPython(fix_notification_table, reverse_fix_notification_table),
    ]
